### PR TITLE
Make the jar executable, it will show an error message if directly executed

### PR DESCRIPTION
**Pull request by kaeptmblaubaer1000**
not-a-program

### CODE REVIEW

**Comment by parzivail** [comment]
What purpose does this serve?

**Comment by kaeptmblaubaer1000** [comment]
If someone thinks this is an executable program, he gets information what this is instead.

**Comment by parzivail** [comment]
I'm not familiar with Swing, is it possible to have a link in that dialog box? I think overall it'd be better if the box just said "This is a Forge mod for Minecraft 1.7.10. Please install it as one, do not run this file directly. For more information, see: https://minecraft.gamepedia.com/Mods/Installing_Forge_mods".

**Comment by kaeptmblaubaer1000** [comment]
not-a-program
It now looks this way.

**Comment by parzivail** [comment]
Looks great.

**Pull request merged**
